### ISSUE TITLE
Something wrong with offset calculation?

### ISSUE THREAD

**Issue by arsenalahm** [asukiaaa/MPU9250_asukiaaa#14]
Hello! In your README, the offset should be calculated as

_maxXOffset = - (magXMax + magXMin) / 2_

but in ./examples/GetMagOffset.ino, line 64, 65 and 66, the code is

_maxXOffset = - (magXMax - magXMin) / 2_

Is it a mistake or am I wrong?

**Comment by asukiaaa** [comment]
I took mistakes about them.
[I correct GetMagOffset](https://github.com/asukiaaa/MPU9250_asukiaaa/commit/71e31d2021f29457ee9bf20fddaa851dc620bad2) and released 1.5.7.
(You can download 1.5.7 after few hours or a day.)
Thank you for the information.

**Comment by arsenalahm** [comment]
Thank a lot!
