### ISSUE TITLE
Get temperature of sensor

### ISSUE THREAD

**Issue by O60PMOT** [asukiaaa/MPU9250_asukiaaa#7]
Hello, do you update to getting temperature of sensor?

**Comment by O60PMOT** [comment]
i'm added in cpp file:
#define MPU9250_ADDR_TEMP_OUT_H   0x41
#define MPU9250_ADDR_TEMP_OUT_L   0x42

int16_t MPU9250::readTemp() {
  uint8_t temp;
  i2cRead(address, MPU9250_ADDR_TEMP_OUT_H, 2, &temp);
  return temp;
}

in h file:
  int16_t readTemp();

and i have 21.08 in result of:
Tmp = ((float) mySensor.readTemp()) / 333.87 + 21;
- but real temp is 26C

**Comment by asukiaaa** [comment]
I also tried to use temperature before but it seems not accurate and heated bu itself.
There fore I don't add function to get temperature because it it is worthless.

**Comment by O60PMOT** [comment]
i need to contol temp inside box, tell me please, where is my error in measuring degrees Celsius?

**Comment by asukiaaa** [comment]
I don't know correct process to get temperature but it has ±4 difference.(3.1Gyroscope Specifications in [datasheet](http://www.invensense.com/wp-content/uploads/2015/02/PS-MPU-9250A-01-v1.1.pdf)) so your code might be correct.
I suggest you to use other module to measure temperature.

**Comment by asukiaaa** [comment]
Sorry the `±4 difference` seems not mean the accuracy of temperature sensor.
I cannot find accuracy about that.

The following function is mentioned at `4.23Registers 65 and 66 –Temperature Measuremen` on [register map](http://www.invensense.com/wp-content/uploads/2017/11/RM-MPU-9250A-00-v1.6.pdf).
```
TEMP_degC = ((TEMP_OUT –RoomTemp_Offset)/Temp_Sensitivity) + 21degC
```

You may need some offset.

**Comment by asukiaaa** [comment]
Your code may breaking memory.
You need to define length 2 uint8_t and merge them like this.
```c
int16_t MPU9250::readTemp() {
uint8_t temp[2];
  i2cRead(address, MPU9250_ADDR_TEMP_OUT_H, 2, &temp);
  return (((uint16_t)) temp[1] << 8 | temp[0]);
}
```

**Comment by O60PMOT** [comment]
thank you! its works!

**Comment by asukiaaa** [comment]
My pleasure.
